
- name: Install python dependency for Debian
  become: true
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: true
    state: latest 
  with_items:
    - build-essential
    - make 
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libssl-dev
    - libffi-dev
    - curl