---
  
- name: Download get-pip.py
  shell: curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
  args:
    warn: false

- name: Pyhton{{ python_version }} pip instalation
  become: true
  shell: /usr/local/bin/python{{ python_version[:3] }} /tmp/get-pip.py --trusted-host pypi.python.org
