---

- import_tasks: debian_dependency.yaml
  when: ansible_os_family == "Debian"

- import_tasks: redhat_dependency.yaml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Download Python Source
  get_url:
    url: https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz
    dest: /tmp

- name: Extract python={{python_version}}.tgz into /tmp
  unarchive:
    src: /tmp/Python-{{python_version}}.tgz
    dest: /tmp

- name: Configure python
  shell: "sh configure --enable-optimizations --with-ssl"
  args:
    chdir: /tmp/Python-{{python_version}}

- make: 
    chdir: /tmp/Python-{{python_version}}
    target: altinstall

- name: "Make Alias to python{{ python_version }} version"
  shell: "echo 'alias python=/usr/local/bin/python{{ python_version[:3] }}' >> /home/vagrant/.bashrc"
  when: make_alias

- include_tasks: install_pip.yaml
  when: (python_version[:1] == "3" and python_version[2:] | float < 4.0 | float) or (python_version[:1] == "2" and python_version[2:] | float < 7.9 | float)

# - include_tasks: install_pipenv.yaml
