---

- name: Install python dependency for Debian
  become: true
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: true
    state: latest 
  with_items:
    - build-essential
    - make 
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev

- name: Install python dependency for Centos or Red Hat Enterprise Linux
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum:
    name: "{{ item }}"
    update_cache: true
    state: latest 
  with_items:
    - "@Development tools"
    - openssl-devel 
    - libffi-devel
    - bzip2-devel
    - sqlite-devel
    - zlib-devel
    - yum-utils
    - llvm
    - xz
    - tk-devel
    - ncurses-devel
    - libselinux-python

- name: Download Python Source
  get_url:
    url: https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz
    dest: /tmp

- name: Extract python={{python_version}}.tgz into /tmp
  unarchive:
    src: /tmp/Python-{{python_version}}.tgz
    dest: /tmp

- name: Configure python
  shell: "sh configure --enable-optimizations"
  args:
    chdir: /tmp/Python-{{python_version}}

- make: 
    chdir: /tmp/Python-{{python_version}}
    target: altinstall

- name: "Make Alias to python{{ python_version }} version"
  shell: "echo 'alias python=python{{ python_version[:3] }}' >> /home/vagrant/.bashrc"
  when: make_alias

# - debug:  
#     msg: "System {{ python_version[2:] }}"
#   when: python_version[2:] | float < 7.1 | float
